spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: false
    refresh:
      enabled: false
    loadbalancer:
      eager-load:
        clients: whatsapp-svc
  application:
    name: schoolers-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB





otel:
  traces:
    exporter: none
  metrics:
    exporter: none
  logs:
    exporter: console
  instrumentation:
    micrometer:
      enabled: true
    http:
      client:
        emit-experimental-telemetry: true
  propagators: "tracecontext,baggage,b3"


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
    propagation:
      produce: w3c,b3,b3_multi
      consume: w3c

jwt:
  issuer: schoolers.com
  expiration-millis: 3600000
  public:
    key: |

  private:
    key: |
      

security:
  max-failed-attempts: 5
  lock-duration-minutes: 30
  challenge-expiration-minutes: 5


cors:
  allowed-origins: "*"


file:
  max-size: 102121212132

