spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: true
    refresh:
      enabled: false
    discovery:
      enabled: false
  application:
    name: schoolers-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB





otel:
  traces:
    exporter: none
  metrics:
    exporter: none
  logs:
    exporter: console
  instrumentation:
    micrometer:
      enabled: true
    http:
      client:
        emit-experimental-telemetry: true
  propagators: "tracecontext,baggage,b3"


management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
    propagation:
      produce: w3c,b3,b3_multi
      consume: w3c

jwt:
  issuer: schoolers.com
  expiration-millis: 3600000
  public:
    key: {PUBLIC_KEY}
  private:
    key: {PRIVATE_KEY}

security:
  max-failed-attempts: ${SECURITY_MAX_FAILED_ATTEMPT:3}
  lock-duration-minutes: ${SECURITY_LOCK_DURATION_MINUTES:30}
  challenge-expiration-minutes: ${SECURITY_CHALLENGE_EXPIRATION_MINUTES:1}


cors:
  allowed-origins: "*"

school:
  name: "SMA Negeri 1 Jakarta"


crypto:
  secret-key: {CRYPTO_SECRET_KEY}

scheduler:
  learning-session-cron: "0 0 3 * * *"

firebase:
  type: {FIREBASE_TYPE:service_account}
  project-id: {FIREBASE_PROJECT_ID}
  private-key-id: {FIREBASE_PRIVATE_KEY_ID}
  private-key: {FIREBASE_PRIVATE_KEY}
  client-email: {FIREBASE_CLIENT_EMAIL}
  client-id: {FIREBASE_CLIENT_ID}
  auth-uri: {FIREBASE_AUTH_URI:-https://accounts.google.com/o/oauth2/auth}
  token-uri: {FIREBASE_TOKEN_URI:-https://oauth2.googleapis.com/token}
  auth-provider-x509-cert-url: {FIREBASE_AUTH_PROVIDER_X509_CERT_URL:-https://www.googleapis.com/oauth2/v1/certs}
  client-x509-cert-url: {FIREBASE_CLIENT_X509_CERT_URL:-https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40schoolers-4e844.iam.gserviceaccount.com}
  universe-domain: {FIREBASE_UNIVERSE_DOMAIN:googleapis.com}

